apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-logs-to-kinesis
  namespace: default
spec:
  selector:
    matchLabels:
      app: fluentd-logs-to-kinesis
  template:
    metadata:
      name: fluentd-logs-to-kinesis
      labels:
        app: fluentd-logs-to-kinesis
    spec:
      containers:
      - name: fluentd-logs-to-kinesis
        image: stridespark/kubernetes-fluentd-kinesis
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: varrundockersock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: KINESIS_STREAM_NAME
          value: "stridespark-app-logs"
      volumes:
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
